services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_user: postgres
      POSTGRES_DB: DesafioNovaWeb
    ports:
      - "5432:5432"
  
  web:
    image: contato-image
    depends_on:
      - db
    ports:
      - "5000:5000"